world: "world"
border:
  initialSize: 128        # Initial size of the world border
  increment: 128          # Size increment per cycle
  maxDays: 300            # Maximum number of days during which the border will expand
  maxSize: 29999984       # Maximum size of the world border(server default: 29999984)
  transitionTime: 180     # Animation time for border expansion (in seconds)
  waitTime: 10            # Days to wait between border expansions
  centerX: 0.0            # X-coordinate of the border center
  centerZ: 0.0            # Z-coordinate of the border center
  autoExpand: true        # Should the borders expand automatically(Turns On/Off the plugin)
  notifyPlayers: true     # Should players be notified about border updates
  logUpdates: true        # Should changes to the border be logged to the console
  bluemapIntegration: true