name: FreiheitPlugin
version: '0.1-BETA'
main: me.wv3ntly.freiheitPlugin.FreiheitPlugin
api-version: '1.21'
load: POSTWORLD
commands:
  worldbarrier:
    description: Manage the world border
    usage: /worldbarrier [set|setCenter|setWaitTime|setMaxDays|setIncrement|setTransitionTime|debug] <arguments>